version: "3.8"

services:
  api-gateway:
    build: ./forumapp-api-gateway
    ports:
      - "8010:8010"

  users:
    build: ./forumapp-users
    ports:
      - "8000:8000"

  replies:
    build: ./forumapp-replies
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  threads:
    build: ./forumapp-threads
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
